name: Build wheels for all platforms

on:
  push:
    branches:
    - feat/zlib-ng
  pull_request:
    branches:
    - master
  workflow_dispatch: {}

jobs:
  build-wheels-windows:
    name: Build Wheels (Windows)
    runs-on: [self-hosted, windows-10]
    steps:
      - name: Environment setup
        run: echo "ZLIB_ROOT=${{ env.HOMEPATH }}\zlib-ng-install" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Install Python dependencies
        run: |
          python3 -m pip install cibuildwheel==2.3.1 requests

      - name: Display environment
        run: "ls env:"

      - name: "Get zlib-ng"
        run: ci/get_zlib_win.ps1

      # TODO - Setup bash by default on Windows runners
      - name: "Add bash.exe to path"
        if: always() && runner.os == 'Windows'
        run: echo "C:\Program Files\Git\bin" >> $GITHUB_PATH

      - name: Build wheels
        run: |
          set -o errexit
          cibuildwheel --print-build-identifiers
          cibuildwheel --output-dir wheelhouse .
          python ci/bundle_hdf5_whl.py wheelhouse

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel-windows
          path: wheelhouse

  build-wheels-linux:
    name: Build Wheels (Linux)
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Environment setup
        run: |
          mkdir $HOME/hdf5-install
          echo "HDF5_DIR=${{ env.HOME }}/hdf5-install" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Install Python dependencies
        run: |
          python3 -m pip install cibuildwheel==2.3.1

      - name: Display environment
        run: env

      - name: Build zlib-ng
        run: ci/build_zlib.sh

      - name: Build HDF5
        run: ci/get_hdf5_if_needed.sh

      - name: Build wheel
        bash: |
          set -o errexit
          cibuildwheel --print-build-identifiers
          cibuildwheel --output-dir wheelhouse .

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel-linux
          path: wheelhouse


